pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/maazabdulbasith/Chatterbox.git'
            }
        }
        
        stage('Build') {
            steps {
                sh 'docker build -t chatter-box:latest .'
            }
        }
        
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        
        stage('Deploy') {
            steps {
                sh 'kubectl apply -f deployment.yaml'
            }
        }
    }
}
